### ISSUE TITLE
webpage going blank

### ISSUE THREAD

**Issue by m00p** [TraderSamwise/tealstreet#30]
when a limited order is placed the whole page get blank white.

I need to refresh to see the page agian.

I recorded it so it's more clear whats going on.
https://imgur.com/a/Xpk6FwZ

It also happens when the browser is maximized. So nothing to do with the small size window.

This started happening somewhere previous week...

**Comment by m00p** [comment]
It's have it also on firefox.

**Comment by m00p** [comment]
I don't know if you did anything but it is fixed.

Don't have it anymore

**Comment by TraderSamwise** [comment]
ya i pushed a quick fix. Thanks for taking the time to record this! Let me know if it happens again
